const express = require('express')
const app = express()
const port = 4001

const cors = require('cors')

const eventsHandler = require('./handlers/events')
const eventTypesHandler = require('./handlers/event-types')
const serversHandler = require('./handlers/servers')
const cargoShipHandler = require('./handlers/cargo-ship')
const skillsetsHandler = require('./handlers/skillsets')
const classesHandler = require('./handlers/classes')
const newsHandler = require('./handlers/news')
const festivalsHandler = require('./handlers/festivals')
const instancesHandler = require('./handlers/instances')
const itemsBuildingsHandler = require('./handlers/items-buildings')
const itemsCropsHandler = require('./handlers/items-crops')
const itemsHandler = require('./handlers/items')
const mountsHandler = require('./handlers/npcs-mounts')
const mountsObtainTypesHandler = require('./handlers/npcs-mounts-obtain-types')
const mountsTypesHandler = require('./handlers/npcs-mounts-types')
const questsCategoriesHandler = require('./handlers/quests-categories')
const questsDailiesHandler = require('./handlers/quests-dailies')
const questsReferenceHandler = require('./handlers/quests-reference')
const questsHandler = require('./handlers/quests')
const recipeHandler = require('./handlers/recipe')
const recipeCategoryHandler = require('./handlers/recipe-category')
const recipeCategoriesHandler = require('./handlers/recipe-categories')
const recipeVocationHandler = require('./handlers/recipe-vocation')
const recipeProductHandler = require('./handlers/recipe-product')
const skillsHandler = require('./handlers/skills')
const tradePacksHandler = require('./handlers/trade-packs')
const tradePacksReferenceHandler = require('./handlers/trade-packs-reference')
const vocationsHandler = require('./handlers/vocations')
const zonesClimatesHandler = require('./handlers/zones-climates')
const zonesContinentsHandler = require('./handlers/zones-continents')
const blueSaltBondsHandler = require('./handlers/blue-salt-bonds')
const npcsHandler = require('./handlers/npcs')
const doodadsHandler = require('./handlers/doodads')
const titlesHandler = require('./handlers/titles')
const usersHandler = require('./handlers/users')
const eventHandler = require('./handlers/events-event')
const searchProductHandler = require('./handlers/search-product')
const searchMaterialHandler = require('./handlers/search-material')
const recipeMaterialHandler = require('./handlers/recipe-material')
const recipeMaterialItemHandler = require('./handlers/recipe-material-item')
const recipeProductlHandler = require('./handlers/recipe-product')
const meHandler = require('./handlers/me')
const newsPostHandler = require('./handlers/news-post')
const commentHandler = require('./handlers/comment')
const commentIdHandler = require('./handlers/comment-id')
const commentByPostHandler = require('./handlers/comment-by-post')

app.use(cors())

app.use((req, res, next) => {
  console.log(req.url)
  next()
})

app.get('/', (req, res) => {
  res.send('Hello World!')
})

app.get('/service/me', meHandler)
app.get('/service/news', newsHandler) // ?page=${page}
app.get('/service/news/:postId', newsPostHandler)
app.get('/service/comment', commentHandler)
app.get('/service/comment/byPost/:postId', commentByPostHandler)
app.get('/service/comment/:commentId', commentIdHandler)
app.get('/service/items', itemsHandler) // ?ids=${itemIds}
app.get('/service/items/crops', itemsCropsHandler)
app.get('/service/items/buildings', itemsBuildingsHandler)
app.get('/service/recipe/product/:itemId', recipeProductHandler)
app.get('/service/recipe/product', recipeProductlHandler)
app.get('/service/recipe/material/:itemId', recipeMaterialItemHandler)
app.get('/service/recipe/material', recipeMaterialHandler)
app.get('/service/recipe/vocation/:vocation', recipeVocationHandler)
app.get('/service/recipe', recipeHandler) // ?ids=${recipeIds}
app.get('/service/recipe/categories', recipeCategoriesHandler)
app.get('/service/recipe/categories/:category', recipeCategoryHandler) // ?cat1=${subCat1}&cat2=${subCat2}
app.get('/service/vocations', vocationsHandler)
app.get('/service/search/product', searchProductHandler)
app.get('/service/search/material', searchMaterialHandler)
app.get('/service/events/types', eventTypesHandler)
app.get('/service/events/:eventId', eventHandler)
app.get('/service/events', eventsHandler)
app.get('/service/users', usersHandler) // ?usernames=${names}
app.get('/service/skills', skillsHandler) // ?ids=${skillIds}
app.get('/service/skills/skillsets', skillsetsHandler)
app.get('/service/skills/classes', classesHandler)
app.get('/service/npcs/mounts', mountsHandler)
app.get('/service/npcs/mounts/types', mountsTypesHandler)
app.get('/service/npcs/mounts/obtainTypes', mountsObtainTypesHandler)
app.get('/service/quests', questsHandler) // ?ids=${questIds}
app.get('/service/quests/categories', questsCategoriesHandler)
app.get('/service/quests/dailies', questsDailiesHandler)
app.get('/service/quests/reference', questsReferenceHandler)
app.get('/service/titles', titlesHandler) // ?ids=${titleIds}
app.get('/service/festivals', festivalsHandler)
app.get('/service/instances', instancesHandler)
app.get('/service/npcs', npcsHandler) // ?ids=${npcIds}
app.get('/service/doodads', doodadsHandler) // ?ids=${doodadIds}
app.get('/service/zones/climates', zonesClimatesHandler)
app.get('/service/zones/continents', zonesContinentsHandler)
app.get('/service/trade-packs', tradePacksHandler)
app.get('/service/trade-packs/reference', tradePacksReferenceHandler)
app.get('/service/servers', serversHandler)
app.get('/service/blue-salt-bonds', blueSaltBondsHandler)
app.get('/service/cargo-ship', cargoShipHandler)

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})
